services:
  api:
    image: smarttasks-api
    build:
      context: .
      dockerfile: SmartTasks/Dockerfile   
    environment:
        - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - "8080:8080"
    depends_on:
      - cache    

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web: 
    image: smarttasks-web
    build:
      context: .
      dockerfile: SmartTasks.Web/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - api
  